import { HealthData, addDays, dateKey, frequencies, observations, rangeLogs } from './health';
export type Answer = { source: string; text: string }[];
export interface AIService { answerHealthQuestion(question:string,data?:HealthData):Promise<Answer>; summarizeHealthHistory(data:HealthData):Promise<string>; generateVisitSummary(data:HealthData):Promise<string>; retrieveRelevantResearch(question:string):Promise<string[]>; }
export class DevelopmentAIService implements AIService {
 async answerHealthQuestion(question:string,data?:HealthData):Promise<Answer> { const q=question.toLowerCase();const personal=data?await this.summarizeHealthHistory(data):'Personalization is off. Your health logs were not included.'; let context='This development assistant provides recorded observations and appointment prompts. Live research retrieval is not connected.';let clinician='Which changes in my history would be useful to investigate further?';if(q.includes('lab')){context='Lab interpretation requires the test’s units, laboratory reference range, and your clinical context. This demo does not interpret results.';clinician='What does this result mean in my medical context, and is follow-up needed?';}else if(q.includes('medication')){context='Changes recorded after a medication starts do not show that the medication caused them.';clinician='Can we review the timing of my recorded symptoms and medication changes?';}else if(q.includes('cycle'))clinician='What additional cycle information should I track, and when should we follow up?';else if(q.includes('snack'))context='Food guidance and live research are not connected in this demo. You can record meals and discuss options that suit your needs with your care team.';return [{source:'Your data',text:personal},{source:'Research',text:context},{source:'Community experiences',text:'Not connected. No community statistics or anecdotes are used.'},{source:'Questions for your clinician',text:clinician}]; }
 async summarizeHealthHistory(data:HealthData) { const end=dateKey();const logs=rangeLogs(data,addDays(end,-89),end);return `${logs.length} days logged in the last 90 days. ${frequencies(logs).slice(0,3).map(([s,n])=>`${s}: ${n} days`).join('; ')}. ${observations(data,addDays(end,-89),end).map(o=>o.text).join(' ')}`; }
 async generateVisitSummary(data:HealthData){return this.summarizeHealthHistory(data);}
 async retrieveRelevantResearch(){return [];}
}
export const aiService:AIService=new DevelopmentAIService();
